#!/usr/bin/env python3
"""
dependency_graph.py — Resolve skill dependencies, detect cycles, and export Mermaid/DOT graphs.
"""

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.resolve()
INDEX_FILE = REPO_ROOT / 'skills.json'
DOCS_DIR = REPO_ROOT / 'docs'
GRAPH_MD = DOCS_DIR / 'DEPENDENCY_GRAPH.md'
GRAPH_MMD = DOCS_DIR / 'dependency_graph.mmd'


def load_index():
    if not INDEX_FILE.exists():
        print("skills.json not found. Run build_index.py first.")
        sys.exit(1)
    with open(INDEX_FILE, 'r', encoding='utf-8') as f:
        return json.load(f)


def build_dependency_graph():
    index_data = load_index()
    skills = index_data['skills']

    dep_map = {}
    rev_map = {}
    all_deps_count = 0

    for name, meta in skills.items():
        deps = meta.get('dependencies', [])
        dep_map[name] = deps
        all_deps_count += len(deps)
        for d in deps:
            rev_map.setdefault(d, []).append(name)

    # Detect cycle (Tarjan or DFS)
    visited = {}
    cycles = []

    def dfs(node, path):
        visited[node] = 1
        path.append(node)
        for neighbor in dep_map.get(node, []):
            if visited.get(neighbor) == 1:
                cycle_start = path.index(neighbor)
                cycles.append(path[cycle_start:] + [neighbor])
            elif visited.get(neighbor) == 0 or neighbor not in visited:
                dfs(neighbor, path)
        path.pop()
        visited[node] = 2

    for skill_name in dep_map:
        if visited.get(skill_name, 0) == 0:
            dfs(skill_name, [])

    # Render Mermaid graph
    mmd_lines = ["graph TD"]
    for skill_name, deps in sorted(dep_map.items()):
        for d in deps:
            mmd_lines.append(f"    {skill_name.replace('-', '_')}[\"{skill_name}\"] --> {d.replace('-', '_')}[\"{d}\"]")

    mmd_content = "\n".join(mmd_lines)

    # Render Markdown report
    md_lines = [
        "# Skill Dependency Graph & Resolution Matrix\n",
        "> Auto-generated by `scripts/dependency_graph.py`.",
        f"> **Total Skills Analyzed**: {len(skills)}",
        f"> **Declared Dependencies**: {all_deps_count}",
        f"> **Circular Dependencies Detected**: {len(cycles)}\n",
        "---\n",
    ]

    if cycles:
        md_lines.append("## ⚠️ Circular Dependencies Detected\n")
        for c in cycles:
            md_lines.append(f"- `{' -> '.join(c)}`")
        md_lines.append("\n---\n")

    md_lines.append("## Skill Prerequisites Summary\n")
    md_lines.append("| Skill | Direct Prerequisites | Dependent Skills (Dependents) |")
    md_lines.append("|---|---|---|")

    for name, meta in sorted(skills.items()):
        deps = dep_map.get(name, [])
        dependents = rev_map.get(name, [])
        deps_str = ", ".join(f"`{d}`" for d in deps) if deps else "*None*"
        dependents_str = ", ".join(f"`{d}`" for d in dependents) if dependents else "*None*"
        md_lines.append(f"| `{name}` | {deps_str} | {dependents_str} |")

    md_lines.append("\n---\n")
    md_lines.append("## Visual Dependency Graph (Mermaid)\n")
    md_lines.append("```mermaid")
    md_lines.append(mmd_content)
    md_lines.append("```\n")

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    GRAPH_MD.write_text("\n".join(md_lines), encoding='utf-8')
    GRAPH_MMD.write_text(mmd_content, encoding='utf-8')

    print(f"Generated dependency graph: {GRAPH_MD} ({all_deps_count} total dependency edges)")


if __name__ == '__main__':
    build_dependency_graph()
