#!/usr/bin/env python3
"""
export_skills.py — Compile agent skills into multi-client instruction formats.

Supported formats:
  --format cursor      → .cursorrules (project root)
  --format copilot     → .github/copilot-instructions.md
  --format windsurf    → .windsurfrules (project root)
  --format all         → all three

Usage:
  python3 scripts/export_skills.py --format cursor
  python3 scripts/export_skills.py --format all --skills-dir ./skills --output-dir ./exports
  python3 scripts/export_skills.py --format copilot --include google-style-python,google-style-typescript
  python3 scripts/export_skills.py --list
"""

import argparse
import re
import sys
from pathlib import Path

try:
    import yaml
    _HAS_YAML = True
except ImportError:
    _HAS_YAML = False

# ── YAML frontmatter parser ────────────────────────────────────────────────────

def strip_frontmatter(content: str) -> tuple[dict, str]:
    """Extract YAML frontmatter and return (meta dict, remaining content).

    Uses PyYAML when available (handles multiline block scalars like
    `description: >`). Falls back to a simple line parser otherwise.
    """
    meta: dict = {}
    if not content.startswith('---'):
        return meta, content
    end = content.find('\n---', 3)
    if end == -1:
        return meta, content
    frontmatter_raw = content[3:end]
    body = content[end + 4:].lstrip('\n')

    if _HAS_YAML:
        try:
            parsed = yaml.safe_load(frontmatter_raw)
            meta = parsed if isinstance(parsed, dict) else {}
        except Exception:
            pass
    else:
        # Fallback: only handles simple key: value (no block scalars)
        for line in frontmatter_raw.splitlines():
            if ':' in line and not line.startswith(' '):
                key, _, val = line.partition(':')
                meta[key.strip()] = val.strip()

    return meta, body


# ── Skill discovery ────────────────────────────────────────────────────────────

def discover_skills(skills_dir: Path, include: list[str] | None = None) -> list[dict]:
    """Return list of skill dicts sorted by name."""
    skills = []
    for skill_path in sorted(skills_dir.iterdir()):
        if not skill_path.is_dir():
            continue
        skill_md = skill_path / 'SKILL.md'
        if not skill_md.exists():
            continue
        name = skill_path.name
        if include and name not in include:
            continue
        content = skill_md.read_text(encoding='utf-8')
        meta, body = strip_frontmatter(content)
        skills.append({
            'name': name,
            'path': skill_path,
            'meta': meta,
            'description': meta.get('description', '').replace('\n', ' ').strip(),
            'body': body,
        })
    return skills


# ── Format renderers ──────────────────────────────────────────────────────────

HEADER_BANNER = """\
# Agent Skills — Compiled Instructions
# Generated by: scripts/export_skills.py
# Source repository: agent-skills
#
# This file is AUTO-GENERATED. Do not edit directly.
# To update: python3 scripts/export_skills.py --format {fmt}
#
# Skills included: {count}
# ─────────────────────────────────────────────────────────────────────────────
"""

def render_cursor(skills: list[dict]) -> str:
    """Render .cursorrules format — plain-text rules Cursor can parse."""
    parts = [HEADER_BANNER.format(fmt='cursor', count=len(skills))]
    for s in skills:
        parts.append(f"## Skill: {s['name']}")
        if s['description']:
            parts.append(f"When to use: {s['description']}\n")
        # Include only the first section of the body (up to 80 lines)
        # to keep the cursorrules file manageable
        lines = s['body'].splitlines()
        preview_lines = []
        heading_count = 0
        for line in lines:
            if line.startswith('## ') or line.startswith('# '):
                heading_count += 1
                if heading_count > 3:
                    preview_lines.append('\n> ... (truncated — see SKILL.md for full rules)')
                    break
            preview_lines.append(line)
        parts.append('\n'.join(preview_lines))
        parts.append('\n---\n')
    return '\n'.join(parts)


def render_copilot(skills: list[dict]) -> str:
    """Render GitHub Copilot instructions markdown format."""
    parts = [
        "# GitHub Copilot Instructions\n",
        "> This file is auto-generated by `scripts/export_skills.py`.",
        "> Source: `agent-skills` repository.\n",
        "---\n",
        "## Available Skills & When to Apply Them\n",
        "Use the following skills based on the task context:\n",
    ]

    # Table of skills
    parts.append("| Skill | When to Apply |")
    parts.append("|---|---|")
    for s in skills:
        desc_short = s['description'][:120] + '...' if len(s['description']) > 120 else s['description']
        desc_short = desc_short.replace('|', '\\|')
        parts.append(f"| `{s['name']}` | {desc_short} |")

    parts.append("\n---\n")
    parts.append("## Skill Rules\n")

    for s in skills:
        parts.append(f"### {s['name']}\n")
        if s['description']:
            parts.append(f"**Trigger**: {s['description']}\n")
        # Full body for copilot — Copilot can handle more context
        parts.append(s['body'])
        parts.append('\n---\n')

    return '\n'.join(parts)


def render_windsurf(skills: list[dict]) -> str:
    """Render .windsurfrules — same format as cursor but with Windsurf header."""
    content = render_cursor(skills)
    return content.replace(
        '# Agent Skills — Compiled Instructions',
        '# Agent Skills — Windsurf Rules'
    ).replace('--format cursor', '--format windsurf')


# ── Output targets ─────────────────────────────────────────────────────────────

FORMATS = {
    'cursor': {
        'render': render_cursor,
        'filename': '.cursorrules',
    },
    'copilot': {
        'render': render_copilot,
        'filename': '.github/copilot-instructions.md',
    },
    'windsurf': {
        'render': render_windsurf,
        'filename': '.windsurfrules',
    },
}


# ── CLI ────────────────────────────────────────────────────────────────────────

def main():
    repo_root = Path(__file__).parent.parent.resolve()

    parser = argparse.ArgumentParser(
        description='Export agent skills to multi-client instruction formats.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        '--format', '-f',
        choices=['cursor', 'copilot', 'windsurf', 'all'],
        default='all',
        help='Output format (default: all)',
    )
    parser.add_argument(
        '--skills-dir',
        type=Path,
        default=repo_root / 'skills',
        help='Path to skills directory (default: ./skills)',
    )
    parser.add_argument(
        '--output-dir',
        type=Path,
        default=repo_root,
        help='Directory to write output files (default: repo root)',
    )
    parser.add_argument(
        '--include', '-i',
        help='Comma-separated list of skill names to include (default: all)',
    )
    parser.add_argument(
        '--list',
        action='store_true',
        help='List discovered skills and exit',
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Print output to stdout instead of writing files',
    )

    args = parser.parse_args()

    include = [s.strip() for s in args.include.split(',')] if args.include else None
    skills = discover_skills(args.skills_dir, include)

    if not skills:
        print(f"No skills found in: {args.skills_dir}", file=sys.stderr)
        sys.exit(1)

    if args.list:
        print(f"Discovered {len(skills)} skills in {args.skills_dir}:\n")
        for s in skills:
            print(f"  {s['name']:<40}  {s['description'][:80]}")
        return

    formats_to_run = list(FORMATS.keys()) if args.format == 'all' else [args.format]

    for fmt in formats_to_run:
        spec = FORMATS[fmt]
        content = spec['render'](skills)
        out_path = args.output_dir / spec['filename']

        if args.dry_run:
            print(f"\n{'='*60}")
            print(f"=== {fmt.upper()} → {out_path} ===")
            print('='*60)
            print(content[:2000])
            if len(content) > 2000:
                print(f'\n... ({len(content) - 2000} more chars) ...')
        else:
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(content, encoding='utf-8')
            print(f"[{fmt}] Written: {out_path} ({len(content):,} chars, {len(skills)} skills)")


if __name__ == '__main__':
    main()
