#!/usr/bin/env python3
"""
export_skills.py — Compile agent skills into multi-client instruction formats.

Supported formats:
  --format agentrules  → .agentrules (project root, default agnostic target)
  --format cursor      → .cursorrules (project root)
  --format copilot     → .github/copilot-instructions.md
  --format windsurf    → .windsurfrules (project root)
  --format all         → all formats

Usage:
  python3 scripts/export_skills.py --format agentrules
  python3 scripts/export_skills.py --format all --skills-dir ./skills --output-dir ./exports
  python3 scripts/export_skills.py --format copilot --include google-style-python,google-style-typescript
  python3 scripts/export_skills.py --list
"""

import argparse
import re
import sys
from pathlib import Path

try:
    import yaml
    _HAS_YAML = True
except ImportError:
    _HAS_YAML = False

# ── YAML frontmatter parser ────────────────────────────────────────────────────

def strip_frontmatter(content: str) -> tuple[dict, str]:
    """Extract YAML frontmatter and return (meta dict, remaining content).

    Uses PyYAML when available (handles multiline block scalars like
    `description: >`). Falls back to a simple line parser otherwise.
    """
    meta: dict = {}
    if not content.startswith('---'):
        return meta, content
    end = content.find('\n---', 3)
    if end == -1:
        return meta, content
    frontmatter_raw = content[3:end]
    body = content[end + 4:].lstrip('\n')

    if _HAS_YAML:
        try:
            parsed = yaml.safe_load(frontmatter_raw)
            meta = parsed if isinstance(parsed, dict) else {}
        except Exception:
            pass
    else:
        # Fallback: only handles simple key: value (no block scalars)
        for line in frontmatter_raw.splitlines():
            if ':' in line and not line.startswith(' '):
                key, _, val = line.partition(':')
                meta[key.strip()] = val.strip()

    return meta, body


# ── Skill discovery ────────────────────────────────────────────────────────────

def discover_skills(skills_dirs: list[Path], include: list[str] | None = None) -> list[dict]:
    """Return list of skill dicts sorted by name, ensuring no duplicates.
    Recursively scans each directory for any files named SKILL.md.
    """
    skills = []
    seen_names = set()
    for skills_dir in skills_dirs:
        if not skills_dir.exists():
            continue
        # Recursively find all SKILL.md files and sort them for deterministic order
        skill_mds = sorted(list(skills_dir.rglob("SKILL.md")))
        for skill_md in skill_mds:
            skill_path = skill_md.parent
            name = skill_path.name
            if include and name not in include:
                continue
            try:
                content = skill_md.read_text(encoding='utf-8')
            except Exception as e:
                print(f"Error reading {skill_md}: {e}", file=sys.stderr)
                continue
            meta, body = strip_frontmatter(content)
            
            # Use frontmatter name if present, fallback to folder name
            skill_name = str(meta.get('name') or name).strip()
            
            if skill_name in seen_names:
                print(f"Warning: Skipping duplicate skill '{skill_name}' found at {skill_path}", file=sys.stderr)
                continue
            
            seen_names.add(skill_name)
            skills.append({
                'name': skill_name,
                'path': skill_path,
                'meta': meta,
                'description': meta.get('description', '').replace('\n', ' ').strip(),
                'body': body,
            })
    # Sort skills alphabetically by name for consistency
    skills.sort(key=lambda s: s['name'].lower())
    return skills



# ── Rules discovery ────────────────────────────────────────────────────────────

def discover_rules(rules_dir: Path) -> list[dict]:
    """Return list of rule dicts sorted by filename from rules_dir."""
    rules = []
    if not rules_dir.exists():
        return rules
    rule_mds = sorted(list(rules_dir.rglob("*.md")))
    for rule_md in rule_mds:
        try:
            content = rule_md.read_text(encoding='utf-8')
        except Exception as e:
            print(f"Error reading {rule_md}: {e}", file=sys.stderr)
            continue
        meta, body = strip_frontmatter(content)
        name = meta.get('title') or rule_md.stem.replace('_', ' ').replace('-', ' ').title()
        rules.append({
            'name': name,
            'filename': rule_md.name,
            'path': rule_md,
            'body': body.strip(),
        })
    return rules


# ── Format renderers ──────────────────────────────────────────────────────────

HEADER_BANNER = """\
# Agent Skills — Compiled Instructions
# Generated by: scripts/export_skills.py
# Source repository: agent-skills
#
# This file is AUTO-GENERATED. Do not edit directly.
# To update: python3 scripts/export_skills.py --format {fmt}
#
# Skills included: {count}
# ─────────────────────────────────────────────────────────────────────────────
"""

def render_generic(skills: list[dict], fmt: str, rules: list[dict] | None = None) -> str:
    """Render generic instruction format — plain-text rules."""
    parts = [HEADER_BANNER.format(fmt=fmt, count=len(skills))]

    if rules:
        parts.append("# ─────────────────────────────────────────────────────────────────────────────")
        parts.append("# CORE ENGINEERING STANDARDS & BOOK RULES")
        parts.append("# ─────────────────────────────────────────────────────────────────────────────\n")
        for r in rules:
            parts.append(f"### Rule: {r['name']}")
            parts.append(r['body'])
            parts.append("\n---\n")

    parts.append("# ─────────────────────────────────────────────────────────────────────────────")
    parts.append("# SKILL RULES")
    parts.append("# ─────────────────────────────────────────────────────────────────────────────\n")

    for s in skills:
        parts.append(f"## Skill: {s['name']}")
        if s['description']:
            parts.append(f"When to use: {s['description']}\n")
        # Include only the first section of the body (up to 80 lines)
        # to keep the rules file manageable
        lines = s['body'].splitlines()
        preview_lines = []
        heading_count = 0
        for line in lines:
            if line.startswith('## ') or line.startswith('# '):
                heading_count += 1
                if heading_count > 3:
                    preview_lines.append('\n> ... (truncated — see SKILL.md for full rules)')
                    break
            preview_lines.append(line)
        parts.append('\n'.join(preview_lines))
        parts.append('\n---\n')
    return '\n'.join(parts)


def render_agentrules(skills: list[dict], rules: list[dict] | None = None) -> str:
    """Render generic .agentrules format."""
    return render_generic(skills, 'agentrules', rules)


def render_cursor(skills: list[dict], rules: list[dict] | None = None) -> str:
    """Render .cursorrules format."""
    return render_generic(skills, 'cursor', rules)


def render_windsurf(skills: list[dict], rules: list[dict] | None = None) -> str:
    """Render .windsurfrules format."""
    return render_generic(skills, 'windsurf', rules)


def render_copilot(skills: list[dict], rules: list[dict] | None = None) -> str:
    """Render GitHub Copilot instructions markdown format."""
    parts = [
        "# GitHub Copilot Instructions\n",
        "> This file is auto-generated by `scripts/export_skills.py`.",
        "> Source: `agent-skills` repository.\n",
        "---\n",
        "## Available Skills & When to Apply Them\n",
        "Use the following skills based on the task context:\n",
    ]

    # Table of skills
    parts.append("| Skill | When to Apply |")
    parts.append("|---|---|")
    for s in skills:
        desc_short = s['description'][:120] + '...' if len(s['description']) > 120 else s['description']
        desc_short = desc_short.replace('|', '\\|')
        parts.append(f"| `{s['name']}` | {desc_short} |")

    parts.append("\n---\n")
    parts.append("## Skill Rules\n")

    for s in skills:
        parts.append(f"### {s['name']}\n")
        if s['description']:
            parts.append(f"**Trigger**: {s['description']}\n")
        # Full body for copilot — Copilot can handle more context
        parts.append(s['body'])
        parts.append('\n---\n')

    return '\n'.join(parts)


# ── Output targets ─────────────────────────────────────────────────────────────

FORMATS = {
    'agentrules': {
        'render': render_agentrules,
        'filename': '.agentrules',
    },
    'cursor': {
        'render': render_cursor,
        'filename': '.cursorrules',
    },
    'copilot': {
        'render': render_copilot,
        'filename': '.github/copilot-instructions.md',
    },
    'windsurf': {
        'render': render_windsurf,
        'filename': '.windsurfrules',
    },
}


# ── CLI ────────────────────────────────────────────────────────────────────────

def main():
    repo_root = Path(__file__).parent.parent.resolve()

    parser = argparse.ArgumentParser(
        description='Export agent skills to multi-client instruction formats.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        '--format', '-f',
        choices=['agentrules', 'cursor', 'copilot', 'windsurf', 'all'],
        default='all',
        help='Output format (default: all)',
    )
    parser.add_argument(
        '--skills-dir',
        type=str,
        default=None,
        help='Comma-separated paths to skills directories (default: ./skills, ./davidondrej-skills/skills, ./agent-scripts/skills)',
    )
    parser.add_argument(
        '--output-dir',
        type=Path,
        default=repo_root,
        help='Directory to write output files (default: repo root)',
    )
    parser.add_argument(
        '--include', '-i',
        help='Comma-separated list of skill names to include (default: all)',
    )
    parser.add_argument(
        '--list',
        action='store_true',
        help='List discovered skills and exit',
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Print output to stdout instead of writing files',
    )

    args = parser.parse_args()

    # Determine skills directories to scan
    if args.skills_dir:
        skills_dirs = [Path(p.strip()).resolve() for p in args.skills_dir.split(',')]
    else:
        # Default scan logic only checks local skills/ folder
        skills_dirs = [repo_root / 'skills']
        # Only keep directories that exist
        skills_dirs = [p for p in skills_dirs if p.exists()]

    include = [s.strip() for s in args.include.split(',')] if args.include else None
    skills = discover_skills(skills_dirs, include)

    rules_dir = repo_root / 'rules'
    rules = discover_rules(rules_dir)

    if not skills:
        dirs_str = ", ".join(str(p) for p in skills_dirs)
        print(f"No skills found in: {dirs_str}", file=sys.stderr)
        sys.exit(1)

    if args.list:
        rel_dirs_str = ", ".join(str(p.relative_to(repo_root)) if repo_root in p.parents or p == repo_root else str(p) for p in skills_dirs)
        print(f"Discovered {len(skills)} skills in [{rel_dirs_str}]:\n")
        for s in skills:
            print(f"  {s['name']:<40}  {s['description'][:80]}")
        return

    formats_to_run = list(FORMATS.keys()) if args.format == 'all' else [args.format]

    for fmt in formats_to_run:
        spec = FORMATS[fmt]
        content = spec['render'](skills, rules)
        out_path = args.output_dir / spec['filename']

        if args.dry_run:
            print(f"\n{'='*60}")
            print(f"=== {fmt.upper()} → {out_path} ===")
            print('='*60)
            print(content[:2000])
            if len(content) > 2000:
                print(f'\n... ({len(content) - 2000} more chars) ...')
        else:
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(content, encoding='utf-8')
            print(f"[{fmt}] Written: {out_path} ({len(content):,} chars, {len(skills)} skills, {len(rules)} book/global rules)")


if __name__ == '__main__':
    main()
