#!/usr/bin/env python3
"""
generate_docs.py — Auto-generate skills catalog, namespace reference, command reference, and health dashboard.
"""

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.resolve()
INDEX_FILE = REPO_ROOT / 'skills.json'
DOCS_DIR = REPO_ROOT / 'docs'


def markdown_cell(value: str) -> str:
    """Escape values embedded in Markdown table cells."""
    return str(value).replace('\\', '\\\\').replace('|', '\\|').replace('\n', ' ')


def load_index():
    if not INDEX_FILE.exists():
        print("skills.json not found. Run build_index.py first.")
        sys.exit(1)
    with open(INDEX_FILE, 'r', encoding='utf-8') as f:
        return json.load(f)


def generate_catalog(data):
    skills = data['skills']
    categories = data['categories']

    cat_grouped = {}
    for name, meta in skills.items():
        cat_grouped.setdefault(meta['category'], []).append(meta)

    md_lines = [
        "# Agent Skills Catalog\n",
        "> Auto-generated by `scripts/generate_docs.py`.",
        f"> **Total Skills**: {len(skills)} across {len(categories)} categories.\n",
        "---\n",
        "## Categories Overview\n",
    ]

    for cat_key, cat_label in categories.items():
        count = len(cat_grouped.get(cat_key, []))
        md_lines.append(f"- **[{cat_label}](#{cat_key})**: {count} skills")

    md_lines.append("\n---\n")

    for cat_key, cat_label in categories.items():
        cat_skills = cat_grouped.get(cat_key, [])
        md_lines.append(f"<a id=\"{cat_key}\"></a>")
        md_lines.append(f"## {cat_label} ({len(cat_skills)} skills)\n")
        md_lines.append("| Skill | Namespace Command | Description |")
        md_lines.append("|---|---|---|")
        for s in sorted(cat_skills, key=lambda x: x['name']):
            md_lines.append(
                f"| `{markdown_cell(s['name'])}` | `{markdown_cell(s['namespace_command'])}` | {markdown_cell(s['description'])} |"
            )
        md_lines.append("\n---\n")

    catalog_file = DOCS_DIR / 'SKILLS_CATALOG.md'
    catalog_file.write_text("\n".join(md_lines), encoding='utf-8')
    print(f"Generated catalog: {catalog_file}")


def generate_namespace_ref(data):
    skills = data['skills']
    namespaces = data['namespaces']
    aliases = data['aliases']

    md_lines = [
        "# Command Namespaces & Slash Command Reference\n",
        "> Auto-generated by `scripts/generate_docs.py`.",
        f"> **Total Namespaced Commands**: {len(namespaces)}",
        f"> **Flat Aliases**: {len(aliases)}\n",
        "---\n",
        "## Namespaced Commands Mapping\n",
        "| Namespace Command | Target Skill | Category | Flat Command |",
        "|---|---|---|---|",
    ]

    for ns_cmd, target_name in sorted(namespaces.items()):
        s = skills.get(target_name, {})
        md_lines.append(f"| `{ns_cmd}` | `{target_name}` | {s.get('category_label', 'General')} | `{s.get('flat_command', '')}` |")

    md_lines.append("\n---\n")
    md_lines.append("## Backward-Compatible Command Aliases\n")
    md_lines.append("| Alias Command | Target Skill | Namespace Command |",)
    md_lines.append("|---|---|---|")
    for alias_name, target_name in sorted(aliases.items()):
        s = skills.get(target_name, {})
        md_lines.append(f"| `/{alias_name}` | `{target_name}` | `{s.get('namespace_command', '')}` |")

    md_lines.append("\n")
    ns_file = DOCS_DIR / 'NAMESPACE_REFERENCE.md'
    ns_file.write_text("\n".join(md_lines), encoding='utf-8')
    print(f"Generated namespace reference: {ns_file}")


def generate_health_dashboard(data):
    skills = data['skills']
    meta = data['metadata']

    total_tokens = sum(s['estimated_tokens'] for s in skills.values())
    avg_tokens = total_tokens // len(skills) if skills else 0

    md_lines = [
        "# Agent Skills System Health & Metrics Dashboard\n",
        "> Auto-generated by `scripts/generate_docs.py`.\n",
        "---\n",
        "## System Metrics Summary\n",
        f"- **Total Registered Skills**: `{len(skills)}`",
        f"- **Total Categories**: `{len(data['categories'])}`",
        f"- **Total Estimated Prompt Tokens**: `{total_tokens:,}` tokens",
        f"- **Average Tokens per Skill**: `{avg_tokens:,}` tokens",
        f"- **Schema Version**: `{meta.get('schema_version')}`",
        f"- **Last Index Update**: `{meta.get('generated_at')}`\n",
        "---\n",
        "## Skill Categories Statistics\n",
        "| Category | Skill Count | Total Tokens | Average Tokens |",
        "|---|---|---|---|",
    ]

    cat_grouped = {}
    for sname, s in skills.items():
        cat_grouped.setdefault(s['category_label'], []).append(s)

    for cat_label, s_list in sorted(cat_grouped.items(), key=lambda x: len(x[1]), reverse=True):
        c_count = len(s_list)
        c_tokens = sum(s['estimated_tokens'] for s in s_list)
        c_avg = c_tokens // c_count if c_count > 0 else 0
        md_lines.append(f"| **{cat_label}** | {c_count} | {c_tokens:,} | {c_avg:,} |")

    md_lines.append("\n")
    health_file = DOCS_DIR / 'HEALTH_DASHBOARD.md'
    health_file.write_text("\n".join(md_lines), encoding='utf-8')
    print(f"Generated health dashboard: {health_file}")


def generate_all_docs():
    data = load_index()
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    generate_catalog(data)
    generate_namespace_ref(data)
    generate_health_dashboard(data)


if __name__ == '__main__':
    generate_all_docs()
