#!/usr/bin/env python3
"""
lint_skills.py — Audit skills repository for duplicates, conflicts, and quality issues.
"""

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.resolve()
INDEX_FILE = REPO_ROOT / 'skills.json'
DOCS_DIR = REPO_ROOT / 'docs'
REPORT_MD = DOCS_DIR / 'DUPLICATE_REPORT.md'


def jaccard_similarity(str1: str, str2: str) -> float:
    set1 = set(re.findall(r'\w+', str1.lower()))
    set2 = set(re.findall(r'\w+', str2.lower()))
    if not set1 or not set2:
        return 0.0
    intersection = set1.intersection(set2)
    union = set1.union(set2)
    return len(intersection) / len(union)


def lint_repository():
    if not INDEX_FILE.exists():
        print("skills.json not found. Run build_index.py first.")
        sys.exit(1)

    with open(INDEX_FILE, 'r', encoding='utf-8') as f:
        index_data = json.load(f)

    skills = index_data['skills']
    aliases = index_data['aliases']

    similar_pairs = []
    alias_conflicts = []
    missing_desc = []
    short_desc = []

    skill_names = list(skills.keys())
    for i in range(len(skill_names)):
        for j in range(i + 1, len(skill_names)):
            name1 = skill_names[i]
            name2 = skill_names[j]
            d1 = skills[name1]['description']
            d2 = skills[name2]['description']

            if not d1 or not d2:
                continue

            sim = jaccard_similarity(d1, d2)
            if sim > 0.65 and name1 != name2:
                similar_pairs.append((name1, name2, sim, d1, d2))

    for name, meta in skills.items():
        desc = meta['description']
        if not desc:
            missing_desc.append(name)
        elif len(desc) < 15:
            short_desc.append(name)

    # Check alias collisions
    alias_targets = {}
    for al, target in aliases.items():
        if al in alias_targets:
            alias_conflicts.append((al, alias_targets[al], target))
        else:
            alias_targets[al] = target

    # Render report
    md_lines = [
        "# Repository Health & Quality Audit Report\n",
        "> Auto-generated by `scripts/lint_skills.py`.",
        f"> **Total Skills Audited**: {len(skills)}",
        f"> **Near-Identical Description Pairs (>65% similarity)**: {len(similar_pairs)}",
        f"> **Missing Descriptions**: {len(missing_desc)}",
        f"> **Alias Conflicts**: {len(alias_conflicts)}\n",
        "---\n",
    ]

    if alias_conflicts:
        md_lines.append("## ⚠️ Alias Collisions\n")
        for al, t1, t2 in alias_conflicts:
            md_lines.append(f"- Alias `/{al}` points to both `{t1}` and `{t2}`")
        md_lines.append("\n---\n")

    if similar_pairs:
        md_lines.append("## 🔍 Near-Identical Skill Pairs (Potential Duplicates)\n")
        md_lines.append("| Skill A | Skill B | Similarity | Description Overview |")
        md_lines.append("|---|---|---|---|")
        for n1, n2, sim, d1, d2 in sorted(similar_pairs, key=lambda x: x[2], reverse=True)[:25]:
            sim_pct = f"{sim*100:.1f}%"
            d_overview = d1[:80] + '...' if len(d1) > 80 else d1
            md_lines.append(f"| `{n1}` | `{n2}` | **{sim_pct}** | {d_overview} |")
        md_lines.append("\n---\n")

    if missing_desc or short_desc:
        md_lines.append("## 📝 Description Quality Warnings\n")
        if missing_desc:
            md_lines.append("**Missing Descriptions**:\n" + ", ".join(f"`{s}`" for s in missing_desc) + "\n")
        if short_desc:
            md_lines.append("**Short/Weak Descriptions**:\n" + ", ".join(f"`{s}`" for s in short_desc) + "\n")
        md_lines.append("\n---\n")

    md_lines.append("## Summary Recommendation\n")
    md_lines.append("Review the near-identical skill pairs above to decide if any should be merged or assigned clearer boundary descriptions.")

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    REPORT_MD.write_text("\n".join(md_lines), encoding='utf-8')
    print(f"Generated quality audit report: {REPORT_MD} ({len(similar_pairs)} potential duplicate pairs found)")


if __name__ == '__main__':
    lint_repository()
