#!/usr/bin/env python3
"""
quality_scorer.py — Audit skills, calculate per-skill quality scores, and generate repository health scorecard.
"""

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.resolve()
INDEX_FILE = REPO_ROOT / 'skills.json'
TELEMETRY_FILE = REPO_ROOT / '.telemetry_log.json'
DOCS_DIR = REPO_ROOT / 'docs'
SCORECARD_MD = DOCS_DIR / 'QUALITY_SCORECARD.md'


def load_telemetry_summary():
    if TELEMETRY_FILE.exists():
        try:
            with open(TELEMETRY_FILE, 'r', encoding='utf-8') as f:
                return json.load(f).get('summary', {})
        except Exception:
            pass
    return {}


def score_skill(name: str, meta: dict, body: str, tele_sum: dict) -> tuple[int, dict]:
    breakdown = {}

    # 1. Doc completeness (20 pts)
    doc_score = 0
    if len(body) > 300: doc_score += 5
    if len(body) > 1000: doc_score += 5
    if '#' in body: doc_score += 5
    if '## When To Use' in body or '## Usage' in body or '## Overview' in body: doc_score += 5
    breakdown['doc_completeness'] = doc_score

    # 2. Metadata quality (20 pts)
    meta_score = 0
    if meta.get('description'): meta_score += 5
    if meta.get('category'): meta_score += 5
    if meta.get('tags') and len(meta['tags']) >= 2: meta_score += 5
    if meta.get('version'): meta_score += 5
    breakdown['metadata_quality'] = meta_score

    # 3. Lifecycle status (15 pts)
    status = meta.get('status', 'stable')
    status_score = 15 if status == 'stable' else (10 if status == 'experimental' else 5)
    breakdown['lifecycle_status'] = status_score

    # 4. Examples / Verification (15 pts)
    example_score = 0
    if 'example' in body.lower() or '```' in body: example_score += 8
    if 'test' in body.lower() or 'verify' in body.lower(): example_score += 7
    breakdown['test_examples'] = example_score

    # 5. Length & Structure Balance (15 pts)
    structure_score = 15 if 200 <= len(body.splitlines()) <= 800 else 10
    breakdown['structure'] = structure_score

    # 6. Telemetry / Activity (15 pts)
    sk_tele = tele_sum.get(name, {})
    tele_score = 15 if sk_tele.get('invocations', 0) > 0 else 10
    breakdown['telemetry'] = tele_score

    total = sum(breakdown.values())
    return total, breakdown


def run_scoring():
    if not INDEX_FILE.exists():
        print("skills.json not found. Run build_index.py first.")
        sys.exit(1)

    with open(INDEX_FILE, 'r', encoding='utf-8') as f:
        index_data = json.load(f)

    skills = index_data['skills']
    tele_sum = load_telemetry_summary()

    scores = {}
    total_repo_score = 0

    for name, meta in skills.items():
        skill_file = REPO_ROOT / meta['rel_path']
        body = ""
        if skill_file.exists():
            body = skill_file.read_text(encoding='utf-8')

        score, breakdown = score_skill(name, meta, body, tele_sum)
        scores[name] = {
            "score": score,
            "status": meta.get('status', 'stable'),
            "category": meta.get('category_label', 'General'),
            "breakdown": breakdown
        }
        total_repo_score += score

    avg_repo_score = round(total_repo_score / len(skills), 1) if skills else 0

    # Write Markdown Report
    md_lines = [
        "# Continuous Quality & Repository Health Scorecard\n",
        "> Auto-generated by `scripts/quality_scorer.py`.",
        f"> **Overall Repository Health Score**: `{avg_repo_score}/100`",
        f"> **Total Skills Audited**: {len(skills)}\n",
        "---\n",
        "## Top Performing Skills (Score 90+)\n",
        "| Skill | Quality Score | Status | Category |",
        "|---|---|---|---|",
    ]

    top_skills = [k for k, v in scores.items() if v['score'] >= 90]
    for sk in sorted(top_skills, key=lambda k: scores[k]['score'], reverse=True)[:30]:
        info = scores[sk]
        md_lines.append(f"| `{sk}` | **{info['score']}/100** | `{info['status']}` | {info['category']} |")

    md_lines.append("\n---\n")
    md_lines.append("## Skills Needing Quality Enhancement (Score < 80)\n")
    md_lines.append("| Skill | Quality Score | Status | Primary Improvement Area |")
    md_lines.append("|---|---|---|---|")

    low_skills = [k for k, v in scores.items() if v['score'] < 80]
    for sk in sorted(low_skills, key=lambda k: scores[k]['score'])[:30]:
        info = scores[sk]
        bd = info['breakdown']
        weakest = min(bd.items(), key=lambda x: x[1])[0].replace('_', ' ').title()
        md_lines.append(f"| `{sk}` | {info['score']}/100 | `{info['status']}` | {weakest} |")

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    SCORECARD_MD.write_text("\n".join(md_lines), encoding='utf-8')
    print(f"Generated quality scorecard: {SCORECARD_MD} (Overall Repository Health: {avg_repo_score}/100)")


if __name__ == '__main__':
    run_scoring()
