#!/usr/bin/env python3
"""
telemetry.py — Instrument skill execution, track metrics, and generate usage reports.
"""

import json
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.resolve()
INDEX_FILE = REPO_ROOT / 'skills.json'
TELEMETRY_FILE = REPO_ROOT / '.telemetry_log.json'
DOCS_DIR = REPO_ROOT / 'docs'
TELEMETRY_MD = DOCS_DIR / 'TELEMETRY_REPORT.md'


def load_telemetry():
    if TELEMETRY_FILE.exists():
        try:
            with open(TELEMETRY_FILE, 'r', encoding='utf-8') as f:
                return json.load(f)
        except Exception:
            pass
    return {"invocations": [], "summary": {}}


def save_telemetry(data):
    TELEMETRY_FILE.write_text(json.dumps(data, indent=2), encoding='utf-8')


def record_invocation(skill_name: str, status: str = "success", duration_ms: int = 1200, tokens_used: int = 350, failure_reason: str = None):
    data = load_telemetry()
    timestamp = time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())
    entry = {
        "skill": skill_name,
        "status": status,
        "duration_ms": duration_ms,
        "tokens_used": tokens_used,
        "timestamp": timestamp,
        "failure_reason": failure_reason,
    }
    data["invocations"].append(entry)

    summary = data.get("summary", {})
    sk_sum = summary.setdefault(skill_name, {
        "invocations": 0,
        "successes": 0,
        "failures": 0,
        "total_tokens": 0,
        "last_used": None,
    })
    sk_sum["invocations"] += 1
    if status == "success":
        sk_sum["successes"] += 1
    else:
        sk_sum["failures"] += 1
    sk_sum["total_tokens"] += tokens_used
    sk_sum["last_used"] = timestamp

    save_telemetry(data)
    print(f"Recorded invocation for '{skill_name}' ({status}, {tokens_used} tokens).")


def generate_report():
    data = load_telemetry()
    summary = data.get("summary", {})

    if INDEX_FILE.exists():
        with open(INDEX_FILE, 'r', encoding='utf-8') as f:
            all_skills = json.load(f).get('skills', {})
    else:
        all_skills = {}

    used_skills = set(summary.keys())
    all_skill_names = set(all_skills.keys())
    unused_skills = sorted(list(all_skill_names - used_skills))

    md_lines = [
        "# Skill Usage Telemetry & Operational Analytics\n",
        "> Auto-generated by `scripts/telemetry.py`.",
        f"> **Total Registered Skills**: {len(all_skill_names)}",
        f"> **Active Invoked Skills**: {len(used_skills)}",
        f"> **Unused Skills**: {len(unused_skills)}\n",
        "---\n",
        "## High-Value Active Skills\n",
        "| Skill | Invocations | Success Rate | Total Tokens | Last Used |",
        "|---|---|---|---|---|",
    ]

    for sk, sk_sum in sorted(summary.items(), key=lambda x: x[1]['invocations'], reverse=True):
        invs = sk_sum['invocations']
        succs = sk_sum['successes']
        rate = f"{(succs / invs * 100):.1f}%" if invs > 0 else "0%"
        tokens = f"{sk_sum['total_tokens']:,}"
        last_u = sk_sum.get('last_used', 'Never')
        md_lines.append(f"| `{sk}` | {invs} | {rate} | {tokens} | {last_u} |")

    md_lines.append("\n---\n")
    md_lines.append("## Unused Skills (Candidates for Archival / Audit)\n")

    if unused_skills:
        for sk in unused_skills[:50]:
            cat = all_skills.get(sk, {}).get('category_label', 'General')
            md_lines.append(f"- `{sk}` ({cat})")
        if len(unused_skills) > 50:
            md_lines.append(f"\n*... and {len(unused_skills) - 50} more unused skills.*")
    else:
        md_lines.append("*All registered skills have been executed at least once!*")

    md_lines.append("\n")
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    TELEMETRY_MD.write_text("\n".join(md_lines), encoding='utf-8')
    print(f"Generated telemetry report: {TELEMETRY_MD}")


if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == 'record':
        sk_name = sys.argv[2] if len(sys.argv) > 2 else 'systematic-debugging'
        record_invocation(sk_name)
    else:
        generate_report()
